// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniMarket.Data;

#nullable disable

namespace OmniMarket.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251203004731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmniMarket.Models.Produtos", b =>
                {
                    b.Property<int>("idProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProduto"));

                    b.Property<DateTime>("dtRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<int>("idUsuarioVendedor")
                        .HasColumnType("int");

                    b.Property<int>("qtdEstoque")
                        .HasColumnType("int");

                    b.Property<bool>("stAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("txtDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("txtNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<decimal>("vlProduto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idProduto");

                    b.ToTable("TBL_PRODUTOS", (string)null);

                    b.HasData(
                        new
                        {
                            idProduto = 1,
                            dtRegistro = new DateTime(2025, 12, 2, 21, 47, 29, 495, DateTimeKind.Local).AddTicks(220),
                            idCategoria = 1,
                            idUsuarioVendedor = 1,
                            qtdEstoque = 3,
                            stAtivo = true,
                            txtDescricao = "Produto n",
                            txtNome = "Icaro",
                            vlProduto = 200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
